"""
音乐曲库共享配置

供音乐推荐 API、灵音伙伴 Agent 等模块复用，避免多处维护不一致。
"""

from __future__ import annotations

from typing import Optional


MUSIC_RECOMMENDATIONS = {
    "happy": [
        {
            "id": "happy-1",
            "title": "Chillax",
            "artist": "Francisco Alvear · Mixkit",
            "mood_type": "happy",
            "url": "/audio/music-room/happy-chillax.mp3",
            "duration": 144,
            "bpm": 96,
            "texture": "木吉他微光 + 轻松新世纪律动",
            "scene": "午后草地",
            "description": "轻盈但不过分兴奋，适合把好心情慢慢延长。",
            "seed": 1011,
            "audio_mode": "external",
            "cover_gradient": ["#FFD166", "#FFB4A2", "#A8E6CF"],
            "visual_preset": "starlight",
        },
        {
            "id": "happy-2",
            "title": "阳光小跳步",
            "artist": "MoodWave AI",
            "mood_type": "happy",
            "url": "/audio/music-room/happy-yangguang-xiaotiaobu.wav",
            "duration": 96,
            "bpm": 112,
            "texture": "木琴脉冲与暖色节拍",
            "scene": "窗边晨光",
            "description": "像脚步踩在晒过太阳的木地板上。",
            "seed": 1027,
            "audio_mode": "external",
            "cover_gradient": ["#FFDA77", "#FF9E7A", "#B8F2E6"],
            "visual_preset": "starlight",
        },
        {
            "id": "happy-3",
            "title": "午后汽水",
            "artist": "MoodWave AI",
            "mood_type": "happy",
            "url": "/audio/music-room/happy-wuhou-qishui.wav",
            "duration": 112,
            "bpm": 106,
            "texture": "闪烁高音与软鼓点",
            "scene": "夏日街角",
            "description": "带一点汽泡感的治愈明亮。",
            "seed": 1039,
            "audio_mode": "external",
            "cover_gradient": ["#FFE29A", "#FFC6D0", "#9ADAD6"],
            "visual_preset": "starlight",
        },
    ],
    "sad": [
        {
            "id": "sad-1",
            "title": "Finding Myself",
            "artist": "Michael Ramir C. · Mixkit",
            "mood_type": "sad",
            "url": "/audio/music-room/sad-finding-myself.mp3",
            "duration": 134,
            "bpm": 62,
            "texture": "空气感合成器 + 缓慢抬升的旋律",
            "scene": "雨后窗边",
            "description": "不催你变好，先给情绪一个柔软的缓冲层。",
            "seed": 5011,
            "audio_mode": "external",
            "cover_gradient": ["#D9F2D6", "#C8EEF3", "#EFE2FF"],
            "visual_preset": "bloom",
        },
        {
            "id": "sad-2",
            "title": "雨后的小灯",
            "artist": "MoodWave AI",
            "mood_type": "sad",
            "url": "/audio/music-room/sad-yuhou-dexiaodeng.wav",
            "duration": 124,
            "bpm": 60,
            "texture": "缓慢和弦与细微亮点",
            "scene": "夜路尽头",
            "description": "像黑暗里那盏不刺眼的小灯。",
            "seed": 5023,
            "audio_mode": "external",
            "cover_gradient": ["#D8F0D5", "#C2E7EF", "#EADCF9"],
            "visual_preset": "bloom",
        },
        {
            "id": "sad-3",
            "title": "慢慢浮上来",
            "artist": "MoodWave AI",
            "mood_type": "sad",
            "url": "/audio/music-room/sad-manman-fushanglai.wav",
            "duration": 138,
            "bpm": 62,
            "texture": "空气感长垫与暖色回声",
            "scene": "清晨雾气",
            "description": "情绪会慢慢找到重新上浮的力气。",
            "seed": 5039,
            "audio_mode": "external",
            "cover_gradient": ["#D7F0D6", "#CAE9EE", "#EEE4FF"],
            "visual_preset": "bloom",
        },
    ],
    "calm": [
        {
            "id": "calm-1",
            "title": "Smooth Meditation",
            "artist": "Arulo · Mixkit",
            "mood_type": "calm",
            "url": "/audio/music-room/calm-smooth-meditation.mp3",
            "duration": 154,
            "bpm": 72,
            "texture": "柔和铺底与轻雾钟琴",
            "scene": "阳台白纱",
            "description": "像一口慢慢放松下来的呼吸，适合把节奏彻底放慢。",
            "seed": 2013,
            "audio_mode": "external",
            "cover_gradient": ["#CBEFFF", "#E6DFFF", "#F7D9E8"],
            "visual_preset": "ripple",
        },
        {
            "id": "calm-2",
            "title": "云朵慢步",
            "artist": "MoodWave AI",
            "mood_type": "calm",
            "url": "/audio/music-room/calm-yunduo-manbu.wav",
            "duration": 118,
            "bpm": 70,
            "texture": "低频暖垫与流动回声",
            "scene": "云层散步",
            "description": "适合把思绪放慢一点的空间。",
            "seed": 2021,
            "audio_mode": "external",
            "cover_gradient": ["#D9F3FF", "#DCD8FF", "#FBE6F0"],
            "visual_preset": "ripple",
        },
        {
            "id": "calm-3",
            "title": "浅海呼吸",
            "artist": "MoodWave AI",
            "mood_type": "calm",
            "url": "/audio/music-room/calm-qianhai-huxi.wav",
            "duration": 132,
            "bpm": 68,
            "texture": "水纹长音与细小星沙",
            "scene": "清晨海边",
            "description": "平静像潮水一样缓缓靠近。",
            "seed": 2033,
            "audio_mode": "external",
            "cover_gradient": ["#BBE7F6", "#D3C6F2", "#F6D7E7"],
            "visual_preset": "ripple",
        },
    ],
    "anxious": [
        {
            "id": "anxious-1",
            "title": "Nature Meditation",
            "artist": "Arulo · Mixkit",
            "mood_type": "anxious",
            "url": "/audio/music-room/anxious-nature-meditation.mp3",
            "duration": 100,
            "bpm": 84,
            "texture": "柔软环境铺底 + 呼吸感旋律",
            "scene": "林间呼吸",
            "description": "适合在焦虑上头时先把呼吸和注意力拉回来。",
            "seed": 3017,
            "audio_mode": "external",
            "cover_gradient": ["#CDEFFF", "#FFF0A9", "#FFD0D8"],
            "visual_preset": "drift",
        },
        {
            "id": "anxious-2",
            "title": "把线团松开",
            "artist": "MoodWave AI",
            "mood_type": "anxious",
            "url": "/audio/music-room/anxious-baxiantuan-songkai.wav",
            "duration": 114,
            "bpm": 88,
            "texture": "有节律的呼吸鼓点",
            "scene": "黄昏走廊",
            "description": "一层层把紧绷的线慢慢放松。",
            "seed": 3029,
            "audio_mode": "external",
            "cover_gradient": ["#BFE6FF", "#FFEBA8", "#FFD9E6"],
            "visual_preset": "drift",
        },
        {
            "id": "anxious-3",
            "title": "慢慢数到十",
            "artist": "MoodWave AI",
            "mood_type": "anxious",
            "url": "/audio/music-room/anxious-manmanshudao-shi.wav",
            "duration": 120,
            "bpm": 86,
            "texture": "稳定脉冲与暖色底雾",
            "scene": "灯下书桌",
            "description": "给身体一个可跟随的节拍。",
            "seed": 3041,
            "audio_mode": "external",
            "cover_gradient": ["#C6E8FF", "#FFF2C7", "#F7D5E1"],
            "visual_preset": "drift",
        },
    ],
    "angry": [
        {
            "id": "angry-1",
            "title": "Serene Moments",
            "artist": "Ahjay Stelino · Mixkit",
            "mood_type": "angry",
            "url": "/audio/music-room/angry-serene-moments.mp3",
            "duration": 119,
            "bpm": 80,
            "texture": "温和脉冲 + 让情绪降温的氛围底色",
            "scene": "降温通道",
            "description": "不是硬压情绪，而是让身体先从紧绷里退出来。",
            "seed": 4019,
            "audio_mode": "external",
            "cover_gradient": ["#FFB49F", "#FFD29A", "#BFEAD0"],
            "visual_preset": "ember",
        },
        {
            "id": "angry-2",
            "title": "柔软边界",
            "artist": "MoodWave AI",
            "mood_type": "angry",
            "url": "/audio/music-room/angry-rouruan-bianjie.wav",
            "duration": 98,
            "bpm": 82,
            "texture": "低频脉冲与稀疏光点",
            "scene": "风吹窗帘",
            "description": "先稳住自己，再让边界清楚。",
            "seed": 4027,
            "audio_mode": "external",
            "cover_gradient": ["#FFA998", "#F8C48D", "#D5E9C9"],
            "visual_preset": "ember",
        },
        {
            "id": "angry-3",
            "title": "暖风出口",
            "artist": "MoodWave AI",
            "mood_type": "angry",
            "url": "/audio/music-room/angry-nuanfeng-chukou.wav",
            "duration": 110,
            "bpm": 80,
            "texture": "缓释鼓点与升温和弦",
            "scene": "空旷天台",
            "description": "让力量慢慢变成可以呼吸的温度。",
            "seed": 4043,
            "audio_mode": "external",
            "cover_gradient": ["#FFBAA7", "#F7C89B", "#CBE8D2"],
            "visual_preset": "ember",
        },
    ],
    "neutral": [
        {
            "id": "neutral-1",
            "title": "Harp Relax",
            "artist": "Francisco Alvear · Mixkit",
            "mood_type": "neutral",
            "url": "/audio/music-room/neutral-harp-relax.mp3",
            "duration": 121,
            "bpm": 74,
            "texture": "竖琴颗粒 + 清透留白",
            "scene": "白纸和清茶",
            "description": "很安静，但会让平淡日常多一点轻微发亮。",
            "seed": 6013,
            "audio_mode": "external",
            "cover_gradient": ["#F8F4D8", "#E9EEF0", "#DFF3E9"],
            "visual_preset": "ripple",
        },
        {
            "id": "neutral-2",
            "title": "白纸和清茶",
            "artist": "MoodWave AI",
            "mood_type": "neutral",
            "url": "/audio/music-room/neutral-baizhi-heqingcha.wav",
            "duration": 102,
            "bpm": 74,
            "texture": "清透和弦与细小回声",
            "scene": "桌边清茶",
            "description": "很安静，但并不空白。",
            "seed": 6029,
            "audio_mode": "external",
            "cover_gradient": ["#F5F0D6", "#E8EDF0", "#DDF0E7"],
            "visual_preset": "ripple",
        },
        {
            "id": "neutral-3",
            "title": "安静路过",
            "artist": "MoodWave AI",
            "mood_type": "neutral",
            "url": "/audio/music-room/neutral-anjing-luguo.wav",
            "duration": 114,
            "bpm": 78,
            "texture": "柔软木质脉冲与空气感",
            "scene": "傍晚回家路",
            "description": "适合陪伴没有太多起伏的一天。",
            "seed": 6041,
            "audio_mode": "external",
            "cover_gradient": ["#F7F4DE", "#E7ECEF", "#E1F4EA"],
            "visual_preset": "ripple",
        },
    ],
}


def get_music_recommendations(mood_type: Optional[str] = None, limit: int = 20) -> list[dict]:
    if mood_type and mood_type in MUSIC_RECOMMENDATIONS:
        return MUSIC_RECOMMENDATIONS[mood_type][:limit]

    recommendations: list[dict] = []
    for mood_list in MUSIC_RECOMMENDATIONS.values():
        recommendations.extend(mood_list)
    return recommendations[:limit]


def get_companion_music_recommendation(mood_type: str, intensity: int = 5) -> dict:
    tracks = MUSIC_RECOMMENDATIONS.get(mood_type, MUSIC_RECOMMENDATIONS["neutral"])
    if intensity >= 8:
        track = tracks[min(2, len(tracks) - 1)]
        energy = "high"
    elif intensity <= 3:
        track = tracks[0]
        energy = "low"
    else:
        track = tracks[min(1, len(tracks) - 1)]
        energy = "medium"

    return {
        "recommendation_id": track["id"],
        "mood": track["mood_type"],
        "title": track["title"],
        "artist": track["artist"],
        "scene": track.get("scene"),
        "texture": track.get("texture"),
        "url": track.get("url"),
        "duration": track.get("duration"),
        "bpm": track.get("bpm"),
        "energy": energy,
        "style": track.get("visual_preset"),
        "description": track.get("description"),
        "intensity_adjusted": intensity >= 8 or intensity <= 3,
    }
